AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Resources:
  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: DB Secret for MyDBInstance
      Name: cf-db-secret
      GenerateSecretString:
        SecretStringTemplate: '{"username": "masteruser"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: "\"'@/\\"
      Tags:
        - Key: name
          Value: stack-test
Outputs:
  MySecret:
    Value: !Ref MySecret
    Export:
      Name: MySecret
